repos:
- hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-vcs-permalinks
  - id: check-yaml
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - args:
    - --markdown-linebreak-ext=md
    exclude: ^.*\.patch$
    id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0

- hooks:
  - id: markdownlint
  repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.23.2

- hooks:
  - id: shellcheck
  repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.5
- hooks:
  - id: yamllint
  repo: https://github.com/adrienverge/yamllint
  rev: v1.26.1

- hooks:
  - id: flake8
  repo: https://gitlab.com/pycqa/flake8
  rev: 5.0.4

- hooks:
  - alias: ec
    exclude: "(?x)(\n    ^LICENSE\n)\n"
    id: editorconfig-checker
  repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 2.4.0

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.981
  hooks:
    - id: mypy
      args: [src]
      pass_filenames: false
      additional_dependencies:
        - types-requests
        - types-certifi

- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.37.0
